services:
  go_products_db:
    container_name: go_products_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  go_products_api:
    container_name: go_products_api
    image: go_products_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - go_products_db
volumes:
  postgres_data:

networks:
  postgres_network:
